### ISSUE TITLE
Validation issues with verpdf

### ISSUE THREAD

**Issue by actuallyabhi** [nks1990/pdf2pdfa#2]
Please guide me how can i fix this

`<h2 id="PDF/A-1B validation profile">Validation information</h2>
            
Validation Profile: | PDF/A-1B validation profile
-- | --
Compliance: | Failed
Total rules in Profile: | 129
Passed Checks: | 2814
Failed Checks: | 3

Validation information
Validation Profile:	PDF/A-1B validation profile
Compliance: 	Failed
Total rules in Profile:	129
Passed Checks:	2814
Failed Checks:	3
Rule	Status
Specification: ISO 19005-1:2005, Clause: 6.2.3.2, Test number: 2	
All ICCBased colour spaces shall be embedded as ICC profile streams as described in PDF Reference 4.5. The number of color components in the color space described by the ICC profile data must match the number of components actually in the ICC profile. As of PDF 1.4, N must be 1, 3, or 4	Failed
1 occurrences 	[Hide](file:///private/var/folders/v4/2pygnkzs3fg6wj12mgymbggh0000gn/T/veraPDF-tempHTMLReport15448548996099463806.html#)
ICCProfile	
N != null && ((N == 1 && colorSpace == "GRAY") || (N == 3 && (colorSpace == "RGB " || colorSpace == "Lab ")) || (N == 4 && colorSpace == "CMYK"))	
root/document[0]/outputIntents[0]/outputIntents[0]/destProfile[0]
The N entry (value null) in the ICC profile dictionary is missing or does not match the number of components in the embedded ICC profile (color space RGB )

	
Specification: ISO 19005-1:2005, Clause: 6.3.6, Test number: 1	
For every font embedded in a conforming file and used for rendering, the glyph width information in the font dictionary and in the embedded font program shall be consistent	Failed
1 occurrences 	[Hide](file:///private/var/folders/v4/2pygnkzs3fg6wj12mgymbggh0000gn/T/veraPDF-tempHTMLReport15448548996099463806.html#)
Glyph	
renderingMode == 3 || widthFromFontProgram == null || widthFromDictionary == null || Math.abs(widthFromFontProgram - widthFromDictionary) <= 1	
root/document[0]/pages[0](6 0 obj PDPage)/contentStream[0]/operators[330]/usedGlyphs[16](Arial,Bold Arial,Bold 128 0 0 false)
Glyph width 556.15234375 in the embedded font program is not consistent with the Widths entry of the font dictionary (value 750)

	
Specification: ISO 19005-1:2005, Clause: 6.2.3.3, Test number: 2	
DeviceCMYK may be used only if the file has a PDF/A-1 OutputIntent that uses a CMYK colour space	Failed
1 occurrences 	[Hide](file:///private/var/folders/v4/2pygnkzs3fg6wj12mgymbggh0000gn/T/veraPDF-tempHTMLReport15448548996099463806.html#)
PDDeviceCMYK	
gOutputCS != null && gOutputCS == "CMYK"	
root/document[0]/pages[0](6 0 obj PDPage)/contentStream[0]/operators[366]/xObject[0](13 0 obj PDXImage)/imageCS[0]
DeviceCMYK colour space is used without CMYK output intent profile`

**Comment by nks1990** [comment]
All three validation failures reported here have been fixed:

1. **ICC profile `/N` missing** — Fixed: `/N` is now correctly placed on the ICC stream dictionary (not the OutputIntent dict)
2. **Font glyph width mismatch** (code 128, WinAnsiEncoding range 128-159) — Fixed: width metrics now correctly mapped for all WinAnsiEncoding glyphs
3. **DeviceCMYK without CMYK OutputIntent** — Fixed: DeviceRGB and DeviceCMYK color spaces are now replaced with ICCBased equivalents

These fixes are available in v3.1.0 (latest on PyPI). Please update:

```bash
pip install --upgrade pdf2pdfa
```

If you still experience issues after upgrading, feel free to reopen.

**Comment by actuallyabhi** [comment]
Used another PDF, still get few issues.

## Validation information
Validation Profile: | PDF/A-1B validation profile
-- | --
Compliance: | Failed
Total rules in Profile: | 129
Passed Checks: | 7360
Failed Checks: | 572

Validation information
Validation Profile:	PDF/A-1B validation profile
Compliance:	Failed
Total rules in Profile:	129
Passed Checks:	7360
Failed Checks:	572
Rule	Status
[Specification: ISO 19005-1:2005, Clause: 6.3.5, Test number: 1](https://github.com/veraPDF/veraPDF-validation-profiles/wiki/PDFA-Part-1-rules#rule-635-1)	
Embedded font programs shall define all font glyphs referenced for rendering with conforming file	Failed
243 occurrences	[Show](https://github.com/nks1990/pdf2pdfa/issues/2#)


[Specification: ISO 19005-1:2005, Clause: 6.3.6, Test number: 1](https://github.com/veraPDF/veraPDF-validation-profiles/wiki/PDFA-Part-1-rules#rule-636-1)	
For every font embedded in a conforming file and used for rendering, the glyph width information in the font dictionary and in the embedded font program shall be consistent	Failed
323 occurrences	[Show](https://github.com/nks1990/pdf2pdfa/issues/2#)


[Specification: ISO 19005-1:2005, Clause: 6.1.11, Test number: 2](https://github.com/veraPDF/veraPDF-validation-profiles/wiki/PDFA-Part-1-rules#rule-6111-2)	
A file's name dictionary, as defined in PDF Reference 3.6.3, shall not contain the EmbeddedFiles key	Failed
1 occurrences	[Show](https://github.com/nks1990/pdf2pdfa/issues/2#)


[Specification: ISO 19005-1:2005, Clause: 6.3.2, Test number: 3](https://github.com/veraPDF/veraPDF-validation-profiles/wiki/PDFA-Part-1-rules#rule-632-3)	
All fonts used in a conforming file shall conform to the font specifications defined in PDF Reference 5.5. BaseFont - name - (Required) The PostScript name of the font	Failed
2 occurrences	[Show](https://github.com/nks1990/pdf2pdfa/issues/2#)


[Specification: ISO 19005-1:2005, Clause: 6.1.4, Test number: 3](https://github.com/veraPDF/veraPDF-validation-profiles/wiki/PDFA-Part-1-rules#rule-614-3)	
Xref streams shall not be used	Failed
1 occurrences	[Show](https://github.com/nks1990/pdf2pdfa/issues/2#)


[Specification: ISO 19005-1:2005, Clause: 6.1.11, Test number: 1](https://github.com/veraPDF/veraPDF-validation-profiles/wiki/PDFA-Part-1-rules#rule-6111-1)	
A file specification dictionary, as defined in PDF 3.10.2, shall not contain the EF key	Failed
2 occurrences	[Show](https://github.com/nks1990/pdf2pdfa/issues/2#)

**Comment by actuallyabhi** [comment]
@nks1990  I have added another issue list.
